# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nubia/TP1803/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),TP1803)

$(call add-radio-file-sha1-checked,radio/BTFM.bin,801d11e0fc69b7ad6c7163ddb4aec3578fa309df)
$(call add-radio-file-sha1-checked,radio/NON-HLOS.bin,d17bdc59ef75d8a65325959d0aae5dc04b4a591f)
$(call add-radio-file-sha1-checked,radio/abl.elf,2002b8f12c11007f459e7448d8b3517dbe47fd74)
$(call add-radio-file-sha1-checked,radio/aop.mbn,58f5f80a117bf70947d90dd60ebbd2b3be366174)
$(call add-radio-file-sha1-checked,radio/cmnlib.mbn,258c7880a9535438fd920637e2fcbcfbd56d6c33)
$(call add-radio-file-sha1-checked,radio/cmnlib64.mbn,90cb1b66f7be0e9ce6a84f246b1d41756ad4c77d)
$(call add-radio-file-sha1-checked,radio/devcfg.mbn,68e11b8db19a016e0fc73a5497089ca59ce993c8)
$(call add-radio-file-sha1-checked,radio/dspso.bin,29dda807b3c6c50db9e46cc3b9105bad6290c76f)
$(call add-radio-file-sha1-checked,radio/hyp.mbn,0c74f636c4d927b70c1f819fadb239bdab1fcc94)
$(call add-radio-file-sha1-checked,radio/imagefv.elf,2536144c2657240250f36b03349361623da171da)
$(call add-radio-file-sha1-checked,radio/km4.mbn,040d904c99bb88f573ad01371616cad4283d9286)
$(call add-radio-file-sha1-checked,radio/multi_image.mbn,d63b48902872620e5f7e0211113f2f5c84c96aaf)
$(call add-radio-file-sha1-checked,radio/parameter.img,c66326912a9bb12523c228ca9feb097dc39de5b1)
$(call add-radio-file-sha1-checked,radio/qupv3fw.elf,90eb5649e4d61558b7f419659a8de4eef297a358)
$(call add-radio-file-sha1-checked,radio/splash.bin,ff383b29142f4e369fb864e52c60ee46bbb124c2)
$(call add-radio-file-sha1-checked,radio/storsec.mbn,a5c96ad98fc9a0143b75d4a5e1ac2454f1b5cac4)
$(call add-radio-file-sha1-checked,radio/tz.mbn,4bfc7f8df862d4d30cc638ab9cf43422dd055c0f)
$(call add-radio-file-sha1-checked,radio/uefi_sec.mbn,bb6ea577a8d803c934c91a71e802e793933ceaab)
$(call add-radio-file-sha1-checked,radio/xbl.bin,63f3cfb6d665f059d1316ec4aa56c637f05a5be3)
$(call add-radio-file-sha1-checked,radio/xbl_config.bin,100835c3c5e0f6751eb9d675ec3b8c9c77e4e799)

endif
